namespace AACN.API.Service
{
    using AACN.API.Model;
    using AACN.Services;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Net;
    using System.Net.Http;
    using System.Text.RegularExpressions;
    using System.Threading.Tasks;

    public static class Utility
    {
        #region commonFunctions
        public static string RemoveJsonNulls(string str)
        {
            Regex regex = new Regex(UtilityRegExp.JsonNullRegEx);
            string data = regex.Replace(str, string.Empty);
            regex = new Regex(UtilityRegExp.JsonNullArrayRegEx);
            return regex.Replace(data, "[]");
        }

        #endregion

        #region odataQueries

        public static readonly string GetMemberById = "contacts?$filter=(contactid eq '{0}')";
        public static readonly string GetEventById = "aacn_events?$filter=(aacn_eventid eq '{0}')";
        public static readonly string GetAnswerById = "aacn_answers?$filter=(aacn_answerid eq '{0}')";
        public static readonly string getAssessmentbyId = "aacn_assessments?$filter=(aacn_assessmentid eq '{0}')";
        public static readonly string getAssessmentlinebyId = "aacn_assessment_lines?$filter=(aacn_assessment_lineid eq '{0}')";
        public static readonly string getSessionbyId = "aacn_sessions?$filter=(aacn_sessionid eq '{0}')";
        public static readonly string getResponseLinebyId = "aacn_response_lines?$filter=(aacn_response_lineid eq '{0}')";
        public static readonly string getAssessmentLineOptionId = "aacn_assessment_line_options?$filter=(aacn_assessment_line_optionid eq '{0}')";
        public static readonly string getQuestionbyId = "aacn_questions?$filter=(aacn_questionid eq '{0}')";
        public static readonly string getResponsebyId = "aacn_responses?$filter=(aacn_responseid eq '{0}')";
        public static readonly string getSpeakerbyId = "aacn_speakers?$filter=(aacn_speakerid eq '{0}')";
        public static readonly string getSurveyProviderByName = "aacn_survey_providers?$select=aacn_survey_providerid&$filter=(aacn_survey_provider eq '{0}')";


        public static readonly string getAssessmentByNumber = "aacn_assessments?$select=aacn_assessment_description,aacn_assessment_numer,aacn_assessment_title,aacn_assessmentid,aacn_passing_score,_aacn_survey_provider_value,_createdby_value,createdon,_createdonbehalfby_value,_modifiedby_value,modifiedon," +
                    "_modifiedonbehalfby_value,overriddencreatedon&$expand=aacn_assessment_line_assessment_header_aacn_as($select=_aacn_assessment_header_value,aacn_assessment_line_control,aacn_assessment_line_number,aacn_assessment_line_order,aacn_assessment_line_orientation,_aacn_assessment_line_question_value," +
                    "aacn_assessment_line_question_text,_aacn_assessment_line_reference_value,aacn_assessment_line_required,aacn_assessment_line_title,aacn_assessment_line_type," + "aacn_assessment_lineid,aacn_assessment_max_responses,createdon,_modifiedby_value,overriddencreatedon;" +
                    "$expand=aacn_assessment_line_assessment_line_reference($select=_aacn_assessment_header_value,aacn_assessment_line_control,aacn_assessment_line_number,aacn_assessment_line_order,aacn_assessment_line_orientation,_aacn_assessment_line_question_value,aacn_assessment_line_question_text," +
                    "_aacn_assessment_line_reference_value,aacn_assessment_line_required,aacn_assessment_line_title,aacn_assessment_line_type," +
                    "aacn_assessment_lineid,aacn_assessment_max_responses,_createdby_value,createdon))&" +
                    "$filter=(aacn_assessment_number eq '{0}')";


        public static readonly string getAssessmentByNumberNew = "aacn_assessments?$select=aacn_assessment_description,aacn_assessment_numer,aacn_assessment_title,aacn_assessmentid,aacn_passing_score,_aacn_survey_provider_value,_createdby_value,modifiedon,overriddencreatedon&$expand=aacn_assessment_line_assessment_header_aacn_as($select=_aacn_assessment_header_value,aacn_assessment_line_control,aacn_assessment_line_number,aacn_assessment_line_order,aacn_assessment_line_orientation,_aacn_assessment_line_question_value,aacn_assessment_line_question_text,_aacn_assessment_line_reference_value,aacn_assessment_line_required,aacn_assessment_line_title,aacn_assessment_line_type,aacn_assessment_lineid,aacn_assessment_max_responses,_createdby_value,createdon;$expand=aacn_assessment_line_option_assessment_line_aa($select=_aacn_assessment_line_value,aacn_assessment_line_option_number,aacn_assessment_line_option_required,aacn_assessment_line_option_score,aacn_assessment_line_option_sort_order,aacn_assessment_line_optionid,_aacn_assessment_line_question_value,_aacn_assessment_line_question_option_value,aacn_assessment_line_question_option_text,aacn_assessment_line_question_text,_createdby_value,createdon,modifiedon)," +
            "aacn_assessment_line_assessment_line_reference($select=_aacn_assessment_header_value,aacn_assessment_line_control,aacn_assessment_line_number,aacn_assessment_line_order,aacn_assessment_line_orientation,_aacn_assessment_line_question_value,aacn_assessment_line_question_text,_aacn_assessment_line_reference_value,aacn_assessment_line_required,aacn_assessment_line_title,aacn_assessment_line_type,aacn_assessment_lineid,aacn_assessment_max_responses,_createdby_value,createdon,_createdonbehalfby_value;$expand=aacn_assessment_line_option_assessment_line_aa($select=_aacn_assessment_line_value,aacn_assessment_line_option_number,aacn_assessment_line_option_required,aacn_assessment_line_option_score,aacn_assessment_line_option_sort_order,aacn_assessment_line_optionid,_aacn_assessment_line_question_value,_aacn_assessment_line_question_option_value,aacn_assessment_line_question_option_text,aacn_assessment_line_question_text,_createdby_value,createdon)))," +
            "aacn_event_assessment_code_aacn_assessment($select=_aacn_assessment_code_value,aacn_end_date,aacn_event_id,aacn_event_name,aacn_eventid,_aacn_parent_event_value,aacn_start_date,_createdby_value,createdon;$expand=aacn_event_parent_event_aacn_event($select=_aacn_assessment_code_value,aacn_end_date,aacn_event_id,aacn_event_name,aacn_eventid,_aacn_parent_event_value,aacn_start_date,_aacn_survey_provider_value,modifiedon))," +
            "aacn_response_assessment_aacn_assessment($select=_aacn_assessment_value,_aacn_event_value,_aacn_member_value,aacn_response_number,aacn_responseid,_aacn_session_value,_aacn_survey_provider_value,_createdby_value,createdon;$expand=aacn_response_line_response_aacn_response($select=_aacn_answer_value,_aacn_assesment_line_value,_aacn_assessment_line_option_value,_aacn_question_value,aacn_question_text,_aacn_response_value,aacn_response_line_number,aacn_response_lineid,aacn_response_text,utcconversiontimezonecode,versionnumber))," +
            "aacn_session_assessment_code_aacn_assessment($select=_aacn_assessment_code_value,aacn_end_date,aacn_end_time,_aacn_event_id_value,aacn_session_id,aacn_session_name,aacn_sessionid,aacn_start_date,aacn_start_time,_aacn_survey_provider_value,_createdby_value,createdon,statecode,statuscode)" +
            "&$filter=(aacn_assessment_number eq '{0}')"; 
        
        
        
        public static readonly string getAssessmentByNumberNew1 = "aacn_assessments?$select=aacn_assessment_description,aacn_assessment_numer,aacn_assessment_title,aacn_assessmentid,aacn_passing_score,_aacn_survey_provider_value,_createdby_value,modifiedon,overriddencreatedon&$expand=aacn_assessment_line_assessment_header_aacn_as($select=_aacn_assessment_header_value,aacn_assessment_line_control,aacn_assessment_line_number,aacn_assessment_line_order,aacn_assessment_line_orientation,_aacn_assessment_line_question_value,aacn_assessment_line_question_text,_aacn_assessment_line_reference_value,aacn_assessment_line_required,aacn_assessment_line_title,aacn_assessment_line_type,aacn_assessment_lineid,aacn_assessment_max_responses,_createdby_value,createdon;" +
            "$expand=aacn_assessment_line_option_assessment_line_aa($select=_aacn_assessment_line_value,aacn_assessment_line_option_number,aacn_assessment_line_option_required,aacn_assessment_line_option_score,aacn_assessment_line_option_sort_order,aacn_assessment_line_optionid,_aacn_assessment_line_question_value,_aacn_assessment_line_question_option_value,aacn_assessment_line_question_option_text,aacn_assessment_line_question_text,_createdby_value,createdon,modifiedon)," +
            "aacn_assessment_line_assessment_line_reference($select=_aacn_assessment_header_value,aacn_assessment_line_control,aacn_assessment_line_number,aacn_assessment_line_order,aacn_assessment_line_orientation,_aacn_assessment_line_question_value,aacn_assessment_line_question_text,_aacn_assessment_line_reference_value,aacn_assessment_line_required,aacn_assessment_line_title,aacn_assessment_line_type,aacn_assessment_lineid,aacn_assessment_max_responses,_createdby_value,createdon,_createdonbehalfby_value;" +
            "$expand=aacn_assessment_line_option_assessment_line_aa($select=_aacn_assessment_line_value,aacn_assessment_line_option_number,aacn_assessment_line_option_required,aacn_assessment_line_option_score,aacn_assessment_line_option_sort_order,aacn_assessment_line_optionid,_aacn_assessment_line_question_value,_aacn_assessment_line_question_option_value,aacn_assessment_line_question_option_text,aacn_assessment_line_question_text,_createdby_value,createdon)," +
            "aacn_assessment_line_assessment_line_reference($select=_aacn_assessment_header_value,aacn_assessment_line_control,aacn_assessment_line_number,aacn_assessment_line_order,aacn_assessment_line_orientation,_aacn_assessment_line_question_value,aacn_assessment_line_question_text,_aacn_assessment_line_reference_value,aacn_assessment_line_required,aacn_assessment_line_title,aacn_assessment_line_type,aacn_assessment_lineid,aacn_assessment_max_responses,_createdby_value,createdon,overriddencreatedon;" +
            "$expand=aacn_assessment_line_option_assessment_line_aa($select=_aacn_assessment_line_value,aacn_assessment_line_option_number,aacn_assessment_line_option_required,aacn_assessment_line_option_score,aacn_assessment_line_option_sort_order,aacn_assessment_line_optionid,_aacn_assessment_line_question_value,_aacn_assessment_line_question_option_value,aacn_assessment_line_question_option_text,aacn_assessment_line_question_text,createdon,modifiedon)," +
            "aacn_assessment_line_assessment_line_reference($select=_aacn_assessment_header_value,aacn_assessment_line_control,aacn_assessment_line_number,aacn_assessment_line_order,aacn_assessment_line_orientation,_aacn_assessment_line_question_value,aacn_assessment_line_question_text,_aacn_assessment_line_reference_value,aacn_assessment_line_required,aacn_assessment_line_title,aacn_assessment_line_type,aacn_assessment_lineid,aacn_assessment_max_responses,_createdby_value,createdon;" +
            "$expand=aacn_assessment_line_assessment_line_reference($select=_aacn_assessment_header_value,aacn_assessment_line_control,aacn_assessment_line_number,aacn_assessment_line_order,aacn_assessment_line_orientation,_aacn_assessment_line_question_value,aacn_assessment_line_question_text,_aacn_assessment_line_reference_value,aacn_assessment_line_required,aacn_assessment_line_title,aacn_assessment_line_type,aacn_assessment_lineid,aacn_assessment_max_responses,createdon;$expand=aacn_assessment_line_option_assessment_line_aa($select=_aacn_assessment_line_value,aacn_assessment_line_option_number,aacn_assessment_line_option_required,aacn_assessment_line_option_score,aacn_assessment_line_option_sort_order,aacn_assessment_line_optionid,_aacn_assessment_line_question_value,_aacn_assessment_line_question_option_value,aacn_assessment_line_question_option_text,aacn_assessment_line_question_text,createdon,modifiedon,_modifiedonbehalfby_value))))))" +
            "&$filter=(aacn_assessment_number eq '{0}')";


         public static readonly string getAssessmentByNumberNew2 = "aacn_assessments?$select=aacn_assessment_description,statecode,aacn_assessment_numer,aacn_assessment_title,aacn_survey_provider,aacn_assessmentid,aacn_passing_score,_aacn_survey_provider_value,_createdby_value,modifiedon,overriddencreatedon&$expand=aacn_assessment_line_assessment_header_aacn_as($select=_aacn_assessment_header_value,aacn_assessment_line_control,statecode,aacn_assessment_line_number,aacn_assessment_line_order,aacn_assessment_line_orientation,_aacn_assessment_line_question_value,aacn_assessment_line_question_text,_aacn_assessment_line_reference_value,aacn_assessment_line_required,aacn_assessment_line_title,aacn_assessment_line_type,aacn_assessment_lineid,aacn_assessment_max_responses,_createdby_value,createdon;" +
            "$expand=aacn_assessment_line_option_assessment_line_aa($select=_aacn_assessment_line_value,statecode,aacn_assessment_line_option_number,aacn_assessment_line_option_required,aacn_assessment_line_option_score,aacn_assessment_line_option_sort_order,aacn_assessment_line_optionid,_aacn_assessment_line_question_value,_aacn_assessment_line_question_option_value,aacn_assessment_line_question_option_text,aacn_assessment_line_question_text,_createdby_value,createdon,modifiedon)," +
            "aacn_assessment_line_assessment_line_reference($select=_aacn_assessment_header_value,statecode,aacn_assessment_line_control,aacn_assessment_line_number,aacn_assessment_line_order,aacn_assessment_line_orientation,_aacn_assessment_line_question_value,aacn_assessment_line_question_text,_aacn_assessment_line_reference_value,aacn_assessment_line_required,aacn_assessment_line_title,aacn_assessment_line_type,aacn_assessment_lineid,aacn_assessment_max_responses,_createdby_value,createdon,_createdonbehalfby_value;" +
            "$expand=aacn_assessment_line_option_assessment_line_aa($select=_aacn_assessment_line_value,statecode,aacn_assessment_line_option_number,aacn_assessment_line_option_required,aacn_assessment_line_option_score,aacn_assessment_line_option_sort_order,aacn_assessment_line_optionid,_aacn_assessment_line_question_value,_aacn_assessment_line_question_option_value,aacn_assessment_line_question_option_text,aacn_assessment_line_question_text,_createdby_value,createdon)," +
            "aacn_assessment_line_assessment_line_reference($select=_aacn_assessment_header_value,statecode,aacn_assessment_line_control,aacn_assessment_line_number,aacn_assessment_line_order,aacn_assessment_line_orientation,_aacn_assessment_line_question_value,aacn_assessment_line_question_text,_aacn_assessment_line_reference_value,aacn_assessment_line_required,aacn_assessment_line_title,aacn_assessment_line_type,aacn_assessment_lineid,aacn_assessment_max_responses,_createdby_value,createdon,overriddencreatedon;" +
            "$expand=aacn_assessment_line_option_assessment_line_aa($select=_aacn_assessment_line_value,statecode,aacn_assessment_line_option_number,aacn_assessment_line_option_required,aacn_assessment_line_option_score,aacn_assessment_line_option_sort_order,aacn_assessment_line_optionid,_aacn_assessment_line_question_value,_aacn_assessment_line_question_option_value,aacn_assessment_line_question_option_text,aacn_assessment_line_question_text,createdon,modifiedon)," +
            "aacn_assessment_line_assessment_line_reference($select=_aacn_assessment_header_value,statecode,aacn_assessment_line_control,aacn_assessment_line_number,aacn_assessment_line_order,aacn_assessment_line_orientation,_aacn_assessment_line_question_value,aacn_assessment_line_question_text,_aacn_assessment_line_reference_value,aacn_assessment_line_required,aacn_assessment_line_title,aacn_assessment_line_type,aacn_assessment_lineid,aacn_assessment_max_responses,_createdby_value,createdon;" +
            "$expand=aacn_assessment_line_assessment_line_reference($select=_aacn_assessment_header_value,aacn_assessment_line_control,statecode,aacn_assessment_line_number,aacn_assessment_line_order,aacn_assessment_line_orientation,_aacn_assessment_line_question_value,aacn_assessment_line_question_text,_aacn_assessment_line_reference_value,aacn_assessment_line_required,aacn_assessment_line_title,aacn_assessment_line_type,aacn_assessment_lineid,aacn_assessment_max_responses,createdon;" +
            "$expand=aacn_assessment_line_option_assessment_line_aa($select=_aacn_assessment_line_value,statecode,aacn_assessment_line_option_number,aacn_assessment_line_option_required,aacn_assessment_line_option_score,aacn_assessment_line_option_sort_order,aacn_assessment_line_optionid,_aacn_assessment_line_question_value,_aacn_assessment_line_question_option_value,aacn_assessment_line_question_option_text,aacn_assessment_line_question_text,createdon,modifiedon,_modifiedonbehalfby_value)," +
            "aacn_assessment_line_assessment_line_reference($select=_aacn_assessment_header_value,statecode,aacn_assessment_line_control,statecode,aacn_assessment_line_number,aacn_assessment_line_order,aacn_assessment_line_orientation,_aacn_assessment_line_question_value,aacn_assessment_line_question_text,_aacn_assessment_line_reference_value,aacn_assessment_line_required,aacn_assessment_line_title,aacn_assessment_line_type,aacn_assessment_lineid,aacn_assessment_max_responses,_createdby_value,createdon,timezoneruleversionnumber,utcconversiontimezonecode,versionnumber;" +
            "$expand=aacn_assessment_line_option_assessment_line_aa($select=_aacn_assessment_line_value,statecode,aacn_assessment_line_option_number,aacn_assessment_line_option_required,aacn_assessment_line_option_score,aacn_assessment_line_option_sort_order,aacn_assessment_line_optionid,_aacn_assessment_line_question_value,_aacn_assessment_line_question_option_value,aacn_assessment_line_question_option_text,aacn_assessment_line_question_text,createdon)))))))&$filter=(aacn_assessment_number eq '{0}')";


        #endregion
    }

}
